force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Student_DOB__c.field-meta.xml
<CustomField>
    <fullName>Student_DOB__c</fullName>
    <label>Student DOB</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/SOQL_Keywords.cls
public class SOQL_Keywords {
    public static void firstMethod(){
        List<String> stdName = new List<String>{'shilpi','Shanky'};
            
            List<Student__c> stdList= [SELECT Name,Student_Name__c,Student_Phone__c,Student_DOB__c
                                      FROM Student__c
                                      Where Student_Name__c IN: stdName];
        System.debug('StudentInfo: '+stdList);
        
        List<Id> stdSet = new List<Id>{'a005j00000RAbKbAAL','a005j00000QFKE8AAP'};
        List<Student__c> stdList2=[SELECT Name,Student_Name__c,Student_Phone__c,Student_DOB__c
                                      FROM Student__c
                                      Where ID IN: stdSet];
        System.debug('StudentInfo: '+stdList2);
    }
}