force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Student Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Student_State__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>City</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Deposit_Fees__c.field-meta.xml
<CustomField>
    <fullName>Student_Deposit_Fees__c</fullName>
    <label>Student Deposit Fees</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_State__c.field-meta.xml
<CustomField>
    <fullName>Student_State__c</fullName>
    <label>Student State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>State</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Student_Year__c.field-meta.xml
<CustomField>
    <fullName>Student_Year__c</fullName>
    <label>Student Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>First year</fullName>
                <default>true</default>
                <label>First year</label>
            </value>
            <value>
                <fullName>Second year</fullName>
            </value>
            <value>
                <fullName>Third year</fullName>
            </value>
            <value>
                <fullName>Fourth year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentExample.cls
public class StudentExample {
    //custom objects
	public Student__c std;
    
    public StudentExample(){
        std= new Student__c();
        
    }
    
    public void insertStudent(){
        std.Student_Name__c='Arav';
        std.Student_Deposit_Fees__c=20000;
        std.Student_Phone__c='65789456';
        std.Student_Year__c='First year';
        std.Student_State__c='Bihar';
        std.City__c='Patna';
       insert std;
        System.debug('Student record Inserted! '+std.Id);
        
    }
}