force-app/main/default/objects/Course__c/fields/Course_Duration__c.field-meta.xml
<CustomField>
    <fullName>Course_Duration__c</fullName>
    <label>Course Duration</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Course_fees__c.field-meta.xml
<CustomField>
    <fullName>Course_fees__c</fullName>
    <label>Course fees</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Teacher_Phone__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Phone__c</fullName>
    <label>Teacher Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SOQL_Custom.cls
public class SOQL_Custom {
    
	 public void queryMethod(){
         //course is parent here
        List <Course__c> conList=[SELECT Name,Course_fees__c,Course_Duration__c, Teacher__r.Name 
                                  FROM Course__c];//__r for relationship
        for(Course__c con: conList){
            System.debug('Name :: '+con.Name);
            System.debug('Fees :: '+con.Course_fees__c);
            System.debug('Duration :: '+con.Course_Duration__c);
            System.debug('Teacher Name :: '+con.Teacher__r.Name);
            System.debug('\n');
        }
    }
     public void secondMethod(){
        List <Teacher__c> accList=[SELECT Name,Teacher_Phone__c,
                                (SELECT Name,Course_fees__c,Course_Duration__c
                                FROM Courses__r)
                               FROM Teacher__c];//__r for relationship
         
        for( Teacher__c acc: accList){ // object creation so no __r
            System.debug('Name :: '+acc.Name);
            System.debug('Phone :: '+acc.Teacher_Phone__c);
           
            List <Course__c> conList=acc.Courses__r;	//__r as here course is showing relationship
            // no __r cause this one is data type
            // so to fetch the data from related object use __r, for initialisation use __c
            
            for(Course__c con: conList){
            System.debug('Name :: '+con.Name);
            System.debug('FEES :: '+con.Course_fees__c);
            System.debug('Phone :: '+con.Course_Duration__c);
            }
             System.debug('\n');
        } 
     }
    
}