force-app/main/default/objects/Course__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <referenceTo>Teacher__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/CountOfCourses__c.field-meta.xml
<CustomField>
    <fullName>CountOfCourses__c</fullName>
    <label>CountOfCourses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Teacher__c/fields/Teacher_Phone__c.field-meta.xml
<CustomField>
    <fullName>Teacher_Phone__c</fullName>
    <label>Teacher Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/CountCourseCtrl.cls
public class CountCourseCtrl {
    
    public static void beforeInsertCourse(List<Course__c> crsList){
        Set<Id> crsId=new Set<Id>();
        for(Course__c crs:crsList){
            crsId.add(crs.Teacher__c);
            System.debug(crs.Teacher__c);
        }
        List<Teacher__c> teachList=[SELECT Name,Teacher_Phone__c,CountOfCourses__c,
                                    (SELECT Name FROM Courses__r)
                                   FROM Teacher__c 
                                    WHERE ID IN: crsId];
        for(Teacher__c teach:teachList){
            List<Course__c> crs=teach.courses__r;
            teach.CountOfCourses__c=crs.size();
            System.debug(crs.size());
        }
        update teachList;
    }
	
    public static void beforeUpdateCount(List<Course__c> crsOld,List<Course__c> crsNew){
        Set<Id> idListOld=new Set<Id>();
        Set<Id> idListNew=new Set<Id>();
        for(Course__c crs:crsOld){
            idListOld.add(crs.Teacher__c);
            System.debug(crs.Teacher__c);
        }										//collected all older ids of updated list
        for(Course__c crs:crsNew){
            idListNew.add(crs.Teacher__c);
            System.debug(crs.Teacher__c);
        }										//collected all newer ids of updated list
        List<Teacher__c> teachoList=[SELECT Name,Teacher_Phone__c,CountOfCourses__c,
                                    (SELECT Name FROM Courses__r)
                                   FROM Teacher__c 
                                    WHERE ID IN: idListOld];		//old teachers list
        List<Teacher__c> teachnList=[SELECT Name,Teacher_Phone__c,CountOfCourses__c,
                                    (SELECT Name FROM Courses__r)
                                   FROM Teacher__c 
                                    WHERE ID IN: idListNew];		//new teachers list
        for(Teacher__c tc:teachoList){
            List<Course__c> tl=tc.Courses__r;
            tc.CountOfCourses__c=tl.size();
        }
        update teachoList;
        for(Teacher__c tc:teachnList){
            List<Course__c> tl=tc.Courses__r;
            tc.CountOfCourses__c=tl.size();
        }
        update teachnList;
    }
}