force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Passenger Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Assignment6Ctrl.cls
public class Assignment6Ctrl {
	
    public Passenger__c pass {get;set;}
    public Ticket__c tick {get;set;}
    
    public Assignment6Ctrl(){
        pass= new Passenger__c();
        tick= new Ticket__c();
    }
    
    public PageReference toTicket(){
        
        PageReference obj=new PageReference('/apex/Ass6TicPage');
        return obj;
    }
    public PageReference toPassenger(){
        
        PageReference obj=new PageReference('/apex/Ass6Pass');
        return obj;
    }
    public PageReference toFinal(){
        PageReference page = new PageReference('/apex/Ass6FinalPage');
        return page;
    }
    public PageReference saveRecMethod(){
        System.debug('Passenger before insert ::'+pass);
        insert pass;
        System.debug('Passenger Info After Insert ::'+pass);
        tick.Passenger__c=pass.Name;
        insert tick;
        PageReference page = new PageReference('/'+tick.Id);
        return page;
    }
}