force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Passenger Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Total_Fare__c.field-meta.xml
<CustomField>
    <fullName>Total_Fare__c</fullName>
    <formula>Total_KM__c * 20</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Fare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Total_KM__c.field-meta.xml
<CustomField>
    <fullName>Total_KM__c</fullName>
    <label>Total KM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Assignment9Ctrl.cls
public class Assignment9Ctrl {
    public List<Passenger__c> pList {get;set;}
    public List<Ticket__c> tList {get;set;}
    public Boolean isPassenger{get;set;}
    public Boolean isTicket{get;set;}
    
    public Assignment9Ctrl(){
        isPassenger = false;
        isTicket = false;
    }
    
    public void displayPassenger(){
        isPassenger = true;
         isTicket = false;
        pList=[SELECT Name,First_Name__c,Last_Name__c,Email__c,Address__c
              FROM Passenger__c];
    }
    public void displayTicket(){
        isPassenger = false;
        isTicket = True;
        tList=[SELECT Name,Passenger__c,From__c,To__c,Total_Fare__c,Total_KM__c
              FROM Ticket__c];
    }
}