force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Passenger Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <label>Ticket</label>
    <nameField>
        <displayFormat>T-{000}</displayFormat>
        <label>Ticket Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Passenger__c.field-meta.xml
<CustomField>
    <fullName>Passenger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Passenger</label>
    <referenceTo>Passenger__c</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Total_Fare__c.field-meta.xml
<CustomField>
    <fullName>Total_Fare__c</fullName>
    <formula>Total_KM__c * 20</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Fare</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ticket__c/fields/Total_KM__c.field-meta.xml
<CustomField>
    <fullName>Total_KM__c</fullName>
    <label>Total KM</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Assignment10Ctrl.cls
public class Assignment10Ctrl {
    public List<AccWrapperClass> wrapperList{get;set;}
    public String searchName{get;set;}
    public List<Ticket__c> tkt{get;set;}


    public Assignment10Ctrl(){
        wrapperList = new List<AccWrapperClass>();
        List<Passenger__c> psg = [SELECT Name,First_Name__c,Last_Name__c,Email__c,Address__c
              FROM Passenger__c];
        Integer count = 1;
         for(Passenger__c p : psg){
             AccWrapperClass objRef = new AccWrapperClass();
             objRef.isCount = count;
             objRef.psg = p;
             objRef.isSelect = false;
             wrapperList.add(objRef);
             count++;
         }
    }

     
     public void relConMethod(){
        Set<Id> ps= new Set<Id>();
        for(AccWrapperClass wrap:wrapperList){
            if(wrap.isSelect == true){
                ps.add(wrap.psg.Id); 
            }
        }
         tkt = [SELECT Name,Passenger__c,From__c,To__c,Total_Fare__c,Total_KM__c
              FROM Ticket__c WHERE Passenger__r.Id IN: ps];
     }

    public class AccWrapperClass {
        public Integer isCount {get;set;}
        public Passenger__c psg{get;set;}
        public Boolean isSelect{get;set;}

        public AccWrapperClass(){
            isCount = 1;
            psg = new Passenger__c();
            isSelect = false;
        }

    }

 

}